---
title: "03_tables_creation"
output: html_notebook
---

```{r setup, include=FALSE}
#load the data
#load("C:/BIG FILES/Phenotyping/HemodynamicProjectsDatasetFeb18.RData")
```

# Load libs
```{r}
library(tableone)
library(magrittr)
library(officer)
library(xlsx)
library(dplyr)
library(sqldf)
```

# Table 1

```{r}

listVars<-c("Gender","Age","Category"
            ,"duration_Surgery_min","duration_CPB_min","duration_outsideCPB_min","duration_preCPB_min","duration_postCPB_min"
            ,"STS_RiskAlgorithm_median_imp"
            ,"total_pressors_formula_mg" 
            ,"TWA65MAP_total_mmHg","TWA65MAP_CPB_mmHg","TWA65MAP_outsideCPB_mmHg","TWA65MAP_preCPB_mmHg","TWA65MAP_postCPB_mmHg"
,"delta_HCT_pct_median_imp","mean_ef_median_imp","Cross_Clamp_Time_imp"
,"AUC65MAP_total_mmHgmin","AUC65MAP_CPB_mmHgmin","AUC65MAP_outsideCPB_mmHgmin","AUC65MAP_preCPB_mmHgmin","AUC65MAP_postCPB_mmHgmin"    
# Outcomes
,"Any_MAE","Renal_Failure","Death","Stroke","RFDS","RFD","DS","RFS")


catVars<-c("Gender","Category"
           ,"Any_MAE","Renal_Failure","Death","Stroke","RFDS","RFD","DS","RFS"
           ) 

table1 <- CreateTableOne(vars = listVars, data = abp_mean_all_data, factorVars = catVars
                         ,testNormal=oneway.test 
                        #strata is usefull in case we want several columns to stratify by
                         )

table1strat <- CreateTableOne(vars = listVars, data = abp_mean_all_data, factorVars = catVars
                         ,testNormal=oneway.test 
                        ,strata = c("Death")
                        #strata is usefull in case we want several columns to stratify by
                         )
## nonnormal specifies variables to be shown as median [IQR]
# 
# testApprox A function used to perform the large sample approximation based tests. The
# default is chisq.test. This is not recommended when some of the cell have
# small counts like fewer than 5.

table1_printed<-as.data.frame(print(table1, nonnormal ="total_pressors_formula_mg"))
table1strat_printed<-as.data.frame(print(table1strat, nonnormal ="total_pressors_formula_mg"))
table1_final<-cbind(table1_printed,table1strat_printed)
write.xlsx(as.data.frame(print(table1_final)), "table1_final.xlsx")


```

